### ISSUE TITLE
Running Problems

### ISSUE THREAD

**Issue by MaxisclDX** [longzhiwen888/fetch_baidu_index#17]
你好，谢谢你的分享。
在browser.py中，
res = self.browser.execute_script('return PPval.ppt;')
res2 = self.browser.execute_script('return PPval.res2;')
这两行代码运行出现了问题：PPavl is not defined.
请问是怎么回事？

**Comment by longzhiwen888** [comment]
如果这两个报错的话，感觉是你没有登录成功或者没有打开指定的指数页面才这样子吧。你是用的chrome或者firefox浏览器吗？我一般是用chrome

**Comment by longzhiwen888** [comment]
最好是有界面的浏览器可以直观的看到页面是否正常，PhantomJS的话可能不够直观

**Comment by MaxisclDX** [comment]
我用的Firefox浏览器，并且已经登陆成功了，进入了指数页面，浏览器页面显示方面的问题就是一直刷新，没有具体数据，然后程序不会停止。Terminal 中一直提示这地方的问题~

**Comment by MaxisclDX** [comment]
**这是我运行后命令行中报的：**
[I 2016-11-01 15:29:45,165 main:36] 请确保你填写的账号密码能够成功登陆百度
[I 2016-11-01 15:29:52,037 main:47] 登陆成功
[I 2016-11-01 15:29:52,064 main:78] 房价 start
Traceback (most recent call last):
  File "/Users/maxiscl/Desktop/fetch_baidu_index-master/baidu_index/browser.py", line 212, in get_baidu_index
    keyword, start_date, end_date, type_name, area
  File "/Users/maxiscl/Desktop/fetch_baidu_index-master/baidu_index/browser.py", line 123, in get_baidu_index_by_date_range
    res = self.browser.execute_script('return PPval.ppt;')
  File "/Users/maxiscl/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/Users/maxiscl/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Users/maxiscl/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: ReferenceError: PPval is not defined

**Comment by longzhiwen888** [comment]
按你说的应该是浏览器没有正常打开指数页面的问题。可能是超时了吧。我那个browser.py在30行和32行有设置时间

**Comment by longzhiwen888** [comment]
你的火狐浏览器平时打开指数页面正常吗？你换成Chrome试试正常吗

**Comment by MaxisclDX** [comment]
正常呀，可以正常进入百度指数页面人为进行查询呀~
我更改了超时时间，改到5000，1000，还是上面的问题~

**Comment by MaxisclDX** [comment]
方便加个联系方式吗？如果不麻烦的话~

**Comment by longzhiwen888** [comment]
我的邮箱是longzhiwen-478@163.com
