### ISSUE TITLE
使用chrome浏览器也会出现获取不到PPval值的问题

### ISSUE THREAD

**Issue by MacLeeee** [longzhiwen888/fetch_baidu_index#23]
以下是遇到的问题：（我已经把config.ini中browser_sleep 的参数加大了，还是不行）
Traceback (most recent call last):
File "/Users/liran/baiduindex/fetch_baidu_index/baidu_index/browser.py", line 228, in get_baidu_index
`keyword,start_date,` end_date, type_name, `area`
File "/Users/liran/baiduindex/fetch_baidu_index/baidu_index/browser.py", line 130, in get_baidu_index_by_date_range
`res` = self.browser.execute_script('return PPval.ppt;')
File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
'args': converted_args})['value']
File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
self.error_handler.check_response(response)
File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
raise exception_class(message, screen, stacktrace)

WebDriverException: Message: unknown error: PPval is not defined
(Session info: chrome=57.0.2987.133)
(Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.12.4 x86_64)

**Comment by longzhiwen888** [comment]
我跟你的环境一样，不过运行起来挺好的，程序启动的chrome是登录成功了吗？

**Comment by longzhiwen888** [comment]
你用的是什么关键词？

**Comment by MacLeeee** [comment]
chrome登陆成功了啊，关键词用的是500家公司的名称，关键词我都放在task.txt里面了

**Comment by longzhiwen888** [comment]
那个task.txt用我git里面的那几个也一样吗？

**Comment by longzhiwen888** [comment]
你在浏览器里面调试return PPval.ppt; 可以得到结果吗

**Comment by MacLeeee** [comment]
好奇怪，如果用你的task.txt就可以的。但是我的关键字，就是公司名称，就不行。例如：曲美家居，在网站上是可以搜索到的，但是爬取就不成功。

**Comment by MacLeeee** [comment]
浏览器里调试return PPval.ppt ?怎么调试啊？

**Comment by longzhiwen888** [comment]
在chrome下的开发者工具，console面板输入PPval.ppt;

**Comment by longzhiwen888** [comment]
在我这里曲美家居是可以的，python，test这些英文的你那里有报错吗

**Comment by MacLeeee** [comment]
python，test是可以的，我想可能是我直接从csv的文件中把关键字复制到task.txt里产生的问题。可能是字体格式的问题，我打关键词进去是可以的。多谢解答🙏！

**Comment by longzhiwen888** [comment]
嗯，那就是了，可能是编码问题
