### ISSUE TITLE
为什么task里面的关键词会被一次性的输入百度指数进行搜索？

### ISSUE THREAD

**Issue by MacLeeee** [longzhiwen888/fetch_baidu_index#25]
如题，怎么让关键词一个个地进入搜索，我一栏只有一个关键词啊。

**Comment by MacLeeee** [comment]
还有某些关键词会产生以下错误是咋回事？
Traceback (most recent call last):
File "/Users/liran/baiduindex/fetch_baidu_index/baidu_index/browser.py", line 228, in get_baidu_index
keyword, start_date, end_date, type_name, area
File "/Users/liran/baiduindex/fetch_baidu_index/baidu_index/browser.py", line 144, in
get_baidu_index_by_date_range
indexes_enc = all_index_info['data'][type_name][0]['userIndexes_enc']
TypeError: string indices must be integers

**Comment by longzhiwen888** [comment]
关键词是一个个的去搜索啊，获取这个区间内该关键词的数据

**Comment by longzhiwen888** [comment]
那个报错应该是请求的接口数据返回有问题，会重新尝试的，比如你请求的接口给你返回了一个404页面

**Comment by MacLeeee** [comment]
好！谢谢
