### ISSUE TITLE
运行报错，请大神帮忙看看是哪里出了问题。谢谢。

### ISSUE THREAD

**Issue by newsta** [longzhiwen888/fetch_baidu_index#34]
[I 2017-11-05 22:14:49,142 main:39] 请确保你填写的账号密码能够成功登陆百度

Traceback (most recent call last):
  File "C:\Users\**\Desktop\fetch_baidu_index-master\baidu_index\main.py", line 127, in <module>
    main()
  File "C:\Users\**\Desktop\fetch_baidu_index-master\baidu_index\main.py", line 47, in main
    baidu_browser = BaiduBrowser(cookie_json=cookie_json)
  File "C:\Users\**\Desktop\fetch_baidu_index-master\baidu_index\browser.py", line 26, in __init__
    self.browser = browser_driver_class(executable_path=ini_config.executable_path)
  File "C:\Python27\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 62, in __init__
    self.service.start()
  File "C:\Python27\lib\site-packages\selenium\webdriver\common\service.py", line 64, in start
    stdout=self.log_file, stderr=self.log_file)
  File "C:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 87]

**Comment by longzhiwen888** [comment]
你widows下可以正常启动chrome吗？配置了chrome驱动吗
