### ISSUE TITLE
是我的phantomjs版本不对吗？

### ISSUE THREAD

**Issue by jadfi** [longzhiwen888/fetch_baidu_index#4]
您好！我在运行test的时候总是报错：
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    s = BaiduBrowser()
  File "../baidu_index\browser.py", line 17, in __init__
    self.browser = webdriver.PhantomJS()
  File "C:\Python27\lib\site-packages\selenium\webdriver\phantomjs\webdriver.py"
, line 51, in __init__
    self.service.start()
  File "C:\Python27\lib\site-packages\selenium\webdriver\common\service.py", lin
e 88, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)
selenium.common.exceptions.WebDriverException: Message: Can not connect to the S
ervice phantomjs
不知道为什么总连不上phantomjs,我用的是1.9.6

**Comment by longzhiwen888** [comment]
我也不是太清楚，你那个phantomjs添加到环境变量了吗？你的windows系统是xp吗？我记得xp有问题来着

**Comment by longzhiwen888** [comment]
你可以不用phantomjs，我自己有时候就用的webdriver.Firefox()

**Comment by longzhiwen888** [comment]
你可以试试新版本了






在2016年07月07 15时42分, "jadfi"<notifications@github.com>写道:



Reopened #4.
